pipeline {
    
    agent any
    
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm audit fix'
            }
        }
        stage('Test') {
            steps {
                sh 'npm i styled-components'
                sh 'npm install react-router-dom'
                sh 'npm install react-icons --save'
                sh 'npm install --save react-chartjs-2'
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'npm run build'
                sh 'npm start &'
                sh 'echo $! > .pidfile'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(cat .pidfile)'
            }
        }
    }
}
